---
- name: Copy the sources.list
  copy: src=sources.list dest=/etc/apt/sources.list
  notify: 
    - apt-get update

- name: Install tree
  apt: name=tree state=present

- name: Install ntp
  apt: name=ntp state=present
  tags: ntp

- name: ntp configure
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running
  service: name=ntp state=running enabled=yes
  tags: ntp
# - name: Set up iptables rules
  # copy: src=iptables-save dest=/etc/sysconfig/iptables
  # notify: restart iptables
